apiVersion: batch/v1
kind: CronJob
metadata:
  name: ping-job
spec:
  schedule: "*/2 * * * *"  # Runs every 2 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ping-container
            image: busybox
            command: ["sh", "-c", "ping -c 4 8.8.8.8"]
          restartPolicy: OnFailure
